### ISSUE TITLE
Parse error with Promela grammar

### ISSUE THREAD

**Issue by farao** [simonmar/happy#116]
Hi,

I was trying to generate a parser for Promela (the SPIN language) from this grammar: http://spinroot.com/spin/Man/grammar.html - I simply copy/pasted it into a file 'grammar.y' and then executed 'happy grammar.y'. Unfortunately, it just prints "happy: 1: Parse error". How can I find out what's wrong? Does this error message mean there was already a parsing error on line 1? If yes, which part of line 1 does happy not understand?

Thanks for your help,
Marius

**Comment by simonmar** [comment]
That grammar file is not in Happy syntax. The Happy syntax is described in the manual: https://www.haskell.org/happy/doc/html/sec-grammar-files.html
