### ISSUE TITLE
Preprocess templates before sdist

### ISSUE THREAD

**Issue by phadej** [simonmar/happy#144]
As far as I can see, there are no reason to preprocess tempalates using `Setup.hs`.

I'd like to remove `build-type: Custom`, for example by creating a Makefile to preprocess templates
into bundled `data-files`.

There is general motivation that `build-type: Custom` is tricky thing, but also that it uses `ghcProgram`.

**Comment by simonmar** [comment]
Yes, we should do this in the same way as it's done in Alex. I'm short on bandwidth to do it myself, if anyone wants to submit a patch that would be great.
