### ISSUE TITLE
Tag v1.20.0 missing in the repo

### ISSUE THREAD

**Issue by andreasabel** [simonmar/happy#184]
happy 1.20.0 has been released 2020-08-25 by https://hackage.haskell.org/user/int_index but the respective tag seems to be missing in the repo.

Also, I think the repo should bump to 1.20.1 in the cabal file on master to prevent mix-ups of the dev version with the released version.  Before the next release, the version can then be adjusted in the cabal file, should that be necessary.

**Comment by int-index** [comment]
I added the 1.20.0 tag
