### ISSUE TITLE
Version 1.21.0: The program 'happy' is required but it could not be found

### ISSUE THREAD

**Issue by Mikolaj** [simonmar/happy#211]
GHC 8.10.7, cabal 3.4:

```
Downloading  happy-1.21.0
Downloaded   happy-1.21.0
Starting     happy-1.21.0 (exe:happy)
Building     happy-1.21.0 (exe:happy)

Failed to build exe:happy from happy-1.21.0.
Build log (
/home/mikolaj/.cabal/logs/ghc-8.10.7/happy-1.21.0-e-happy-f90d659122467dc006ae1efb35dcd10f113a0857663940bcc9c74e11a4405a6f.log
):
Configuring executable 'happy' for happy-1.21.0..
Preprocessing executable 'happy' for happy-1.21.0..
cabal-3.4.0.0: The program 'happy' is required but it could not be found
```

**Comment by int-index** [comment]
`Cabal` doesn’t understand bootstrapping, so you’ll need to do it manually.

```
cabal install happy -f -bootstrap
cabal install happy -f +bootstrap
```

Then it should work, assuming `$HOME/.cabal/bin` is in your `$PATH`.

**Comment by Bodigrim** [comment]
Could we avoid this flag altogether? What if we declare an internal library (sharing `hs-source-dirs` with `happy` executable), which bootstraps from a parser-combination-based implementation (so it is `happy` stage0) and is used to bootstrap `happy` proper?

**Comment by Ericson2314** [comment]
I have deprecated 1.21 on Hackage before anyone else's workflows get broken. Sorry for the disturbance.
