### ISSUE TITLE
Not-unreasonable grammar takes 17min to compile with GHC2021

### ISSUE THREAD

**Issue by remexre** [simonmar/happy#213]
[This grammar](https://git.sr.ht/~remexre/sylvan/tree/e107162b2ddc6126089b12f1d957f1add6b555d2/item/bootstrap/Language/Sylvan/Parser.y) takes just over 17 minutes to compile, most of which appears to be spent in typechecking. It feels possible that the use of `PartialTypeSignatures` is related, though I'm not particularly sure.

Turning off GHC2021 features and OverloadedStrings, typechecking time is reduced to roughly 8min, which is still really long... (Only removing OverloadedStrings seems to make no difference.)

**Comment by remexre** [comment]
Taken up with GHC, fixed in GHC 9.2.1.

**Comment by Ericson2314** [comment]
Glad to hear it!
