### ISSUE TITLE
Problems running GLR example.

### ISSUE THREAD

**Issue by ltbinsbe** [simonmar/happy#42]
![output](https://cloud.githubusercontent.com/assets/4237463/5800128/bdbf69c0-9fd2-11e4-98ba-bf79d301fc29.png)
My first attempt of running the glr/expr-eval example was using a (nearly) fresh install of the haskell-platform on Ubuntu 14.04. 
This however resulted in an installation of happy-1.19.0, which caused imports to fail (modules Char and System). 
Therefore I installed happy-1.19.5 and tried what can be found in the attachment.

**Comment by thomie** [comment]
You're missing the `--decode` flag. See the `Makefile` and the documentation.

You might need https://github.com/simonmar/happy/pull/57 first as well.
