### ISSUE TITLE
release new version of happy with fixed GLR code gen etc

### ISSUE THREAD

**Issue by cartazio** [simonmar/happy#61]
I'll see about doing a PR to also make it warning clean on 8.0 builds and update the travis ci file
(seems a shame to have a happy release that doesn't have a de-bitrottted glr support :) )

cc @hvr  @bgamari @thoughtpolice

**Comment by erikd** [comment]
It is now warning clean with 8.0 and I added a .travis.yml file to build against the last four major releases of GHC.

**Comment by emc2** [comment]
Re-upping this request, now that the typeclass parser code has been integrated as well

**Comment by hvr** [comment]
Before cutting a release we need to talk about the `.cabal` file. There are a few things to clean up & update, and possibly rethink.

**Comment by simonmar** [comment]
@hvr Do you have specific suggestions or can you point out the problems that need fixing?

**Comment by phadej** [comment]
Would something like: make both development and installing simpler? Though current `Makefile` is only one additional step, which is still required before the release.

```diff
+flag development
+  manual: True
+  default: False
+  description: Development mode, regenerates grammar sources

 executable happy
   hs-source-dirs: src
   main-is: Main.lhs
 
+  if flag(development)
+    hs-source-dirs: src/boot
+    -- causes dependency cycle failure
+    -- build-tools: happy
+  else
+    hs-source-dirs: src/gen
```

(`Parser.hs` and `AttrGrammarParser.hs` are moved to `src/gen`)

**Comment by simonmar** [comment]
I think it would be easier if we had `cabal sdist` generate the files, so that the repo has the `.ly` files but the Hackage package contains the generated source files.

**Comment by phadej** [comment]
I'm not sure it's worth the trouble, that feature would be only usable for `happy` and `alex`, every other package would rather prefer to include (well, maybe not) `.y` files in their `sdist` tarballs?

**Comment by andreasabel** [comment]
This discussion seems to have gone cold, can this issue be closed?

**Comment by Ericson2314** [comment]
Good call, and the bootstrapping issue is now fixed.
