### ISSUE TITLE
License mismatch between Cabal and LICENSE file

### ISSUE THREAD

**Issue by peti** [simonmar/happy#70]
The Cabal file places this code under BSD3 but the LICENSE file contains a BSD2 license.

**Comment by erikd** [comment]
@peti Unfortunately its not currently possible the change that field to `BSD2` because cabal doesn't parse `BSD2`. The error it gives is:
```Warning: 'license: BSD2' is not a recognised license. The known licenses are:
GPL, GPL-2, GPL-3, LGPL, LGPL-2.1, LGPL-3, BSD3, MIT, Apache, Apache-2.0,
PublicDomain, AllRightsReserved, OtherLicense
```
If you want `BSD2` in that field, `BSD2` needs to be added to cabal.

**Comment by peti** [comment]
Well, Cabal certainly *does* support the BSD2 license: http://hackage.haskell.org/package/Cabal-1.24.0.0/docs/Distribution-License.html#t:License. It seems like you're using an old version of Cabal (cabal-install).

**Comment by erikd** [comment]
I am actually using 1.24.0.0 but I still get that warning. Maybe thats a cabal bug.

**Comment by erikd** [comment]
Wow, that's interesting. I was using ghc-7.6.3 for some testing and it does indeed give the above warning even with cabal version 1.24.0.0. If I switch to ghc-8.0.1 the warning disappears.
