### ISSUE TITLE
Version constraint on Base prevents installing on GHC 8.0

### ISSUE THREAD

**Issue by DemiMarie** [simonmar/happy#73]

**Comment by erikd** [comment]
Current git HEAD builds find with ghc-8.0.1 as does the most recent version on Hackage which is 1.19.5.

Which version are you having trouble with and what is the error message?

**Comment by Blaisorblade** [comment]
Both 1.19.5 and 1.19.6 install on GHC 8.0.2, it appears this issue should be closed.
