### ISSUE TITLE
Grammar rule constraints

### ISSUE THREAD

**Issue by liarokapisv** [simonmar/happy#83]
Instead of producing errors depending on the values of matched terminals/non terminals, is it possible to constrain the rule so that it simply doesn't match ?

**Comment by erikd** [comment]
Is it possible to give an example of what you mean?

**Comment by liarokapisv** [comment]
Yes, here is an example. Say my tokens have indentation information. It would
be convenient to be able to write a rule that matches depending on the indentation:

```
sameIndentStmt : stmt {@@ val $1 
                      ; withConstraint (sameIndentationAsLeader (indentation $1))}
sameIndentStmts : sameIndentStmt { [$1] }
                | sameIndentStmt sameIndentStmts {$1 : $2} 

```

Just by reading the user guide it doesn't seem that writing rules like sameIndentStmts is currently supported but I could be missing something. Is something like this supported and if it's not does it seem feasible and/or even desirable to implement?
