### ISSUE TITLE
Generated code using `happyMonad2Reduce` without `-a` leads to kind error

### ISSUE THREAD

**Issue by harpocrates** [simonmar/happy#95]
I unfortunately don't have on hand the grammar that let me trigger this bug (although I'll try to produce one later today or tomorrow). That said, I think it is pretty straightforward to understand the problem. The code template for `happyMonad2Reduce` is [here](https://github.com/simonmar/happy/blob/41fbb827d6fb1761233b015382fd62808abe45cc/templates/GenericTemplate.hs#L234-L248):

```Haskell
happyMonad2Reduce k nt fn ERROR_TOK tk st sts stk
     = happyFail [] ERROR_TOK tk st sts stk
happyMonad2Reduce k nt fn j tk st sts stk =
      case happyDrop k CONS(st,sts) of
        sts1@(CONS(st1@HAPPYSTATE(action),_)) ->
         let drop_stk = happyDropStk k stk
#if defined(HAPPY_ARRAY)
             off = indexShortOffAddr happyGotoOffsets st1
             off_i = PLUS(off,nt)
             new_state = indexShortOffAddr happyTable off_i
#else
             new_state = action
#endif
          in
          happyThen1 (fn stk tk) (\r -> happyNewToken new_state sts1 (r `HappyStk` drop_stk))
```

When `-a` is not present, that reduces to the following:

```Haskell
happyMonad2Reduce k nt fn ERROR_TOK tk st sts stk
     = happyFail [] ERROR_TOK tk st sts stk
happyMonad2Reduce k nt fn j tk st sts stk =
      case happyDrop k CONS(st,sts) of
        sts1@(CONS(st1@HAPPYSTATE(action),_)) ->
         let drop_stk = happyDropStk k tsk
             new_state = action
          in
          happyThen1 (fn stk tk) (\r -> happyNewToken new_state sts1 (r `HappyStk` drop_stk))
```

In this last snippet, the `nt` argument is not used at all. In particular, GHC infers (as it always does) that `nt` has a lifted type. In this case, however, `nt :: Int#`, leading to a kind compilation error in the generated code.

This should be an easy bug to fix, but I'm not sure if you would prefer to fix it by adding a type signature to `happyMonad2Reduce` as a whole or just some sort of type annotation on `nt` in the non-array case.

There exists an easy workaround in the meantime: use `-a`.

**Comment by harpocrates** [comment]
Here is a grammar that triggers this:

```
%name parse prod

%tokentype { Token }

%monad { P } { bindP } { returnP }
%error { error "parse error" }
%lexer { lexer } { EOF }

%token
  IDENT  { Identifier $$ }

%%

prod :: { () }
  : IDENT {%% \_ -> returnP () }

{

data Token = EOF | Identifier String

type P a = String -> (a, String)

bindP :: P a -> (a -> P b) -> P b
bindP p f s = let (x,s') = p s in f x s'

returnP :: a -> P a
returnP = (,)

lexer :: (Token -> P a) -> P a
lexer cont s = cont (case s of { "" -> EOF; _ -> Identifier s }) ""

main = pure ()

}
```

Generated and compiled with

     $ happy -gc  -o compileBug.hs compileBug.y
     $ ghc compileBug.hs
     [1 of 1] Compiling Main             ( compileBug.hs, compileBug.o )

    compileBug.hs:94:38: error:
        • Couldn't match a lifted type with an unlifted type
          When matching the kind of ‘Happy_GHC_Exts.Int#’
        • In the second argument of ‘happyMonad2Reduce’, namely ‘4#’
          In the expression: happyMonad2Reduce 1# 4# happyReduction_1
          In an equation for ‘happyReduce_1’:
              happyReduce_1 = happyMonad2Reduce 1# 4# happyReduction_1

**Comment by simonmar** [comment]
Probably a type annotation on `nt` would be the best way to fix this, I'm not sure if we can give a type signature to `happyMonad2Reduce` in general.
